### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by ShiftedRy** [olathunberg/IP-switcher#2]
First of all thanks for you effort! Your tool is the only one which is capable of assagning multiple IP-addresses to a single interface.

Sadly it seems not really stable on Windows 11, it crashes from time to time.

Greets Georg

**Comment by olathunberg** [comment]
Any information on when or how it crashes? EventLog messages etc?

**Comment by ShiftedRy** [comment]
I switched over to https://github.com/BornToBeRoot/NETworkManager . It's using a Power Shell command to assign multiple IP-Addresses, but thanks for you effort!
